name: Contributor Helper

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions-cool/contributor-helper@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          update-files: 'README.md, README.zh-CN.md'
          update-places: 'CONTRIBUTING.md)./## ğŸ“§ Contact us, CONTRIBUTING.md)ã€‚/## ğŸ“§ è”ç³»æˆ‘ä»¬'
          show-total: false
          style: 'simple'

      - name: Commit and push if changed
        run: |-
          git diff
          git config --local user.name antv
          git config --local user.email antv@antfin.com
          git pull
          git add -A
          git commit -m "ğŸ¤– Auto update contributors" || exit 0
          git push
